#!/usr/bin/env bash
# Install and configure nginx to return a page containing Holberton School
sudo apt-get update -y
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start

